# Generated by Django 3.1.2 on 2020-10-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STTWEBMAIN', '0003_auto_20201008_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='date',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='videos',
            name='title',
            field=models.CharField(default='', max_length=70),
        ),
    ]
