# Generated by Django 3.1.2 on 2020-10-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STTWEBMAIN', '0004_auto_20201015_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='channel',
            field=models.CharField(default='', max_length=30),
        ),
    ]
