# Generated by Django 3.1.2 on 2020-10-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STTWEBMAIN', '0006_auto_20201015_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='tags',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='videos',
            name='tags_2',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='videos',
            name='tags_3',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='videos',
            name='tags_4',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
