# Generated by Django 3.1.2 on 2020-11-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STTWEBMAIN', '0007_auto_20201023_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='searches',
            name='times_searched',
            field=models.IntegerField(default=0),
        ),
    ]
