# Generated by Django 3.1.2 on 2020-11-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STTWEBMAIN', '0008_searches_times_searched'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='', max_length=30)),
                ('total_videos', models.IntegerField(default=0)),
                ('downloaded_videos', models.IntegerField(default=0)),
                ('top_tags', models.CharField(default='', max_length=1000)),
                ('top_tags_2', models.CharField(default='', max_length=1000)),
                ('top_tags_3', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
