# Generated by Django 3.1.2 on 2020-11-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STTWEBMAIN', '0009_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='top_tags_2',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='top_tags_3',
        ),
    ]
