# Generated by Django 3.1.2 on 2020-11-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STTWEBMAIN', '0010_auto_20201117_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='top_search',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
