# Generated by Django 3.1.2 on 2020-11-18 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STTWEBMAIN', '0012_auto_20201118_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='similar_videos_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 13, 2, 17)),
        ),
    ]
