# Generated by Django 3.1.2 on 2020-11-18 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STTWEBMAIN', '0013_auto_20201118_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='subtitles_checked',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 14, 18, 13)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='similar_videos_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 14, 18, 13, 426635)),
        ),
    ]
