# Generated by Django 3.1.3 on 2021-02-04 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STTWEBMAIN', '0016_auto_20210125_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(default='', max_length=30)),
                ('profile_img', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='videos',
            name='similar_videos_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 14, 32, 22, 178314)),
        ),
    ]
