# Generated by Django 3.1.3 on 2021-02-05 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STTWEBMAIN', '0018_auto_20210204_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='managed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videos',
            name='similar_videos_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 14, 32, 12, 44659)),
        ),
    ]
